[workspace]
members = [
    "crate_universe",
    "cargo/crate_graph",
]

[patch.crates-io]
# Until https://github.com/steveklabnik/semver-parser/pull/60 merges.
semver-parser = { git = "https://github.com/illicitonion/semver-parser.git", rev = "ad6589269eab8851f3d5ad362a6b1cd89a1b6693" }
